export { africaTimezones } from './data/africa-timezones.js';
export antarcticaTimezones from './data/antarctica-timezones.js';
export asiaTimezones from './data/asia-timezones.js';
export atlanticTimezones from './data/atlantic-timezones.js';
export australiaTimezones from './data/australia-timezones.js';
export europeTimezones from './data/europe-timezones.js';
export indianTimezones from './data/indian-timezones.js';
export northAmericaTimezones from './data/north-america-timezones.js';
export pacificTimezones from './data/pacific-timezones.js';
export southAmericaTimezones from './data/south-america-timezones.js';
